# Generated by Django 4.1.1 on 2022-09-18 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_post',
            new_name='commentpost',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_user',
            new_name='commentuser',
        ),
    ]
