# Generated by Django 4.1.1 on 2022-09-18 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_comment_post_comment_commentpost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commentpost',
            new_name='commentPost',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commentuser',
            new_name='commentUser',
        ),
    ]
