# Generated by Django 4.1.1 on 2022-09-18 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_commentpost_comment_commentpost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commentPost',
            new_name='comment_post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commentUser',
            new_name='comment_user',
        ),
    ]
