# Generated by Django 4.1.1 on 2022-09-18 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_comment_rating_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='rating_Author',
            new_name='rating_author',
        ),
    ]
