# Generated by Django 4.1.1 on 2022-09-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_rename_rating_author_author_rating_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating_comment',
            field=models.FloatField(default=0.0),
        ),
    ]
