# Generated by Django 4.1.1 on 2022-09-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_comment_rating_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating_comment',
            field=models.IntegerField(default=0),
        ),
    ]
